contact_links:
  - name: 🤔 Questions, General Support, and Help
    url: https://github.com/giladgd/lifecycle-utils/discussions
    about: This issue tracker is not for support questions. Please use GitHub discussions instead.
