name: Test
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install modules
        run: npm ci
      - name: ESLint
        run: npx eslint --ext .js --ext .ts .
      - name: TypeScript validity
        run: npm run test:typescript

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install modules
        run: npm ci
      - name: Run vitest tests
        run: npm run test:vitest -- --coverage --reporter=junit
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/clover.xml
          flags: unittests
          fail_ci_if_error: true

  compile-docs:
    name: Test docs compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install modules
        run: npm ci
      - name: Compile docs
        run: npm run docs:build
